DROP TABLE IF EXISTS Quizzes;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS Answers;
DROP TABLE IF EXISTS Submissions;

CREATE TABLE Quizzes (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE Questions (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Text VARCHAR(100) NOT NULL,
    FOREIGN KEY (QuizId) REFERENCES Quizzes(Id)
);

CREATE TABLE Answers (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Text VARCHAR(100) NOT NULL,
    IsCorrect BOOLEAN NOT NULL,
    FOREIGN KEY (QuizId) REFERENCES Quizzes(Id)
);

CREATE TABLE Submissions (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Score INT NOT NULL,
    FOREIGN KEY (QuizId) REFERENCES Quizzes(Id)
);